server:
  port: 8200

spring:
  application:
    name: user-service


eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka/

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    IFeignActivitService#sendCouponAfterRegisterTimeout(Long):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


