server:
  port: 8100

spring:
  application:
    name: activity-service

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka/


